# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  push:
    # paths:
    #   - "functions/"
    branches: 
      - main

defaults:
  run:
    working-directory: functions      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Npm Install
        run: npm i

      - name: Print Secrets to the Log
        run: |          
          echo "Secrets Envs"
          echo  ${{secrets.SPOTIFY_EXPIRED_TOKEN}}
          echo  ${{secrets.SPOTIFY_MONGO_DATABASE}}
          echo  ${{secrets.SPOTIFY_MONGO_PASSWORD}}
          echo  ${{secrets.SPOTIFY_API}}
          echo  ${{secrets.SPOTIFY_CLIENT_ID}}
          echo  ${{secrets.SPOTIFY_CLIENT_SECRET}}
          echo  ${{secrets.SPOTIFY_REDIRECT_URL}}


      # Runs a single command using the runners shell
      - name: Integration Test
        run: npm run test
        env:
          SPOTIFY_EXPIRED_TOKEN: ${{secrets.SPOTIFY_EXPIRED_TOKEN}}
          SPOTIFY_MONGO_DATABASE: ${{secrets.SPOTIFY_MONGO_DATABASE}}
          SPOTIFY_MONGO_PASSWORD: ${{secrets.SPOTIFY_MONGO_PASSWORD}}
          SPOTIFY_API: ${{secrets.SPOTIFY_API}}
          SPOTIFY_CLIENT_ID: ${{secrets.SPOTIFY_CLIENT_ID}}
          SPOTIFY_CLIENT_SECRET: ${{secrets.SPOTIFY_CLIENT_SECRET}}
          SPOTIFY_REDIRECT_URL: ${{secrets.SPOTIFY_REDIRECT_URL}}
          CI_DEBUG_TRACE: true
          CI: true